/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { initializeFirestore, getFirestore, persistentLocalCache, persistentMultipleTabManager, setLogLevel } from 'firebase/firestore';
import { getStorage, ref, uploadBytes, getDownloadURL, deleteObject } from 'firebase/storage';
import firebaseConfig from '../../firebase-applet-config.json';

// Authentication and Firestore ALWAYS run on the default Firebase 1 project
const app = initializeApp(firebaseConfig);

// Dynamically read custom Firebase config from localStorage if present FOR STORAGE ONLY (Firebase 2)
let storageInstance: any = null;
export let isUsingCustomFirebase = false;

if (typeof window !== 'undefined') {
  const savedCustom = localStorage.getItem('xuongan_custom_firebase_config');
  if (savedCustom) {
    try {
      const parsed = JSON.parse(savedCustom);
      if (parsed && parsed.apiKey && parsed.projectId) {
        isUsingCustomFirebase = true;
        console.log("[Firebase 2 Storage] Initializing custom storage app with project:", parsed.projectId);
        try {
          // Initialize named secondary app to prevent clashes with the primary app
          const customApp = initializeApp(parsed, "custom_storage_app");
          storageInstance = getStorage(customApp);
          console.log("[Firebase 2 Storage] Storage initialized successfully on secondary project.");
        } catch (storageInitErr) {
          console.error("[Firebase 2 Storage] Failed to initialize custom storage app:", storageInitErr);
        }
      }
    } catch (e) {
      console.error("[Firebase] Failed to parse custom Firebase configuration:", e);
    }
  }
}

// Fallback: If no custom config or storage initialization fails, use standard Firebase 1 Storage
if (!storageInstance) {
  try {
    storageInstance = getStorage(app);
    console.log("[Firebase 1 Storage] Default storage initialized successfully.");
  } catch (e) {
    console.warn("[Firebase 1 Storage] Failed to initialize default storage:", e);
  }
}

export const storage = storageInstance;

// CRITICAL: The app will break without passing firestoreDatabaseId if specified
const dbId = (firebaseConfig as any).firestoreDatabaseId;

// Determine if we should bypass the sandbox database id in production or external contexts.
// Sandbox database IDs generated by AI Studio start with 'ai-studio-'.
// When built for production, deployed on GitHub Pages, or packaged as an Android APK,
// the application should fall back to standard '(default)' database ID since the sandbox database
// does not exist in the user's personal Firebase production project 'app-kho-an'.
const isForceDefaultDb = typeof window !== 'undefined' && localStorage.getItem("xuongan_force_default_db") === "true";

// Auto-detect sandbox environment (only development and preview environments generated by AI Studio)
const isSandbox = typeof window !== 'undefined' && (
  window.location.hostname.includes('ais-dev-') || 
  window.location.hostname.includes('ais-pre-') || 
  window.location.hostname.includes('aistudio') ||
  window.location.hostname.includes('ai-studio-')
);

const isProductionOrApk = !isSandbox || (typeof window !== 'undefined' && (
  (window as any).Capacitor || 
  window.location.protocol === 'capacitor:' || 
  window.location.hostname === 'localhost' ||
  window.location.hostname.includes('web.app') ||
  window.location.hostname.includes('firebaseapp.com')
));

const finalDbId = (isForceDefaultDb || isProductionOrApk) ? undefined : dbId;

// Suppress warnings/info logs about connectivity such as "Could not reach Cloud Firestore backend"
setLogLevel('error');

let dbInstance;
try {
  dbInstance = finalDbId 
    ? initializeFirestore(app, {
        localCache: persistentLocalCache({
          tabManager: persistentMultipleTabManager(),
        }),
      }, finalDbId)
    : initializeFirestore(app, {
        localCache: persistentLocalCache({
          tabManager: persistentMultipleTabManager(),
        }),
      });
  console.log("[Firebase] Firestore initialized successfully with persistent local cache.");
} catch (error) {
  console.warn("[Firebase] Failed to initialize Firestore with persistent local cache, falling back to safe getFirestore API: ", error);
  try {
    // Instead of calling initializeFirestore again (which throws "Firestore has already been initialized"), 
    // we retrieve the default or currently active instance safely using getFirestore.
    dbInstance = getFirestore(app);
    console.log("[Firebase] Firestore fallback recovered successfully via getFirestore.");
  } catch (fallbackError: any) {
    console.error("[Firebase] Fatal: Both persistent local cache and getFirestore fallback failed! ", fallbackError);
    
    // Create a safe mock db object to prevent early script compilation/module errors,
    // allowing the clean, descriptive ErrorBoundary to mount and present a clear diagnostic UI to the user.
    dbInstance = {
      _isMock: true,
      type: "firestore",
      app: app,
    } as any;
    
    // Expose the error globally so the mounting component or developer tools can retrieve exact context
    if (typeof window !== "undefined") {
      (window as any).__firebase_init_error = fallbackError;
    }
  }
}

export const db = dbInstance;

export const auth = getAuth(app);

// Namespace helpers for Group Collaboration & Database Pooling (Tính năng Nhóm & Kết hợp liên kết)
export function getNamespaceCollection(collectionName: string): string {
  if (typeof window === 'undefined') return collectionName;
  const groupCode = localStorage.getItem("xuongan_group_code") || "";
  const cleanCode = groupCode.trim().toUpperCase().replace(/[^A-Z0-9_-]/g, "");
  // We keep system logs separate if needed, but partition operational tables
  if (collectionName === 'login_notifications') {
    return collectionName;
  }
  return cleanCode ? `group_${cleanCode}_${collectionName}` : collectionName;
}

export function getSettingsDocId(): string {
  if (typeof window === 'undefined') return "global_settings";
  const groupCode = localStorage.getItem("xuongan_group_code") || "";
  const cleanCode = groupCode.trim().toUpperCase().replace(/[^A-Z0-9_-]/g, "");
  return cleanCode ? `settings_${cleanCode}` : "global_settings";
}

// Custom Error types and helpers as requested by Firebase Integration Skill
export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  };
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null): never {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
      tenantId: auth.currentUser?.tenantId,
      providerInfo: auth.currentUser?.providerData?.map(provider => ({
        providerId: provider.providerId,
        email: provider.email,
      })) || []
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

/**
 * Recursively cleans and sanitizes data before writing to Firestore,
 * ensuring no undefined fields are passed, which would crash Firestore.
 */
export function sanitizeDataForFirestore<T>(data: T): T {
  if (data === undefined) {
    return null as unknown as T;
  }
  if (data === null) {
    return null as unknown as T;
  }
  if (Array.isArray(data)) {
    return data.map(item => sanitizeDataForFirestore(item)) as unknown as T;
  }
  if (typeof data === 'object') {
    // Keep custom Date/Timestamp untouched
    if (data instanceof Date) {
      return data;
    }
    const sanitizedObj: any = {};
    for (const [key, val] of Object.entries(data)) {
      if (val !== undefined) {
        sanitizedObj[key] = sanitizeDataForFirestore(val);
      }
    }
    return sanitizedObj as T;
  }
  return data;
}

/**
 * Convert base64 data URL to standard Blob
 */
function base64ToBlob(base64Data: string, contentType: string = 'image/jpeg'): Blob {
  const sliceSize = 512;
  const base64Clean = base64Data.includes(';base64,') 
    ? base64Data.split(';base64,')[1] 
    : base64Data;
    
  const byteCharacters = atob(base64Clean);
  const byteArrays = [];

  for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
    const slice = byteCharacters.slice(offset, offset + sliceSize);
    const byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }
    const byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }

  return new Blob(byteArrays, { type: contentType });
}

/**
 * Upload an image (base64 string or Blob) directly to Firebase Cloud Storage (Firebase 2)
 */
export async function uploadImageToFirebase(
  fileData: string | Blob,
  fileName: string
): Promise<{ fileUrl: string; filePath: string }> {
  if (!storage) {
    throw new Error("Dịch vụ lưu trữ Firebase Storage chưa được khởi tạo. Vui lòng kiểm tra lại cấu hình.");
  }

  let blob: Blob;
  if (typeof fileData === 'string') {
    const mimeMatch = fileData.match(/^data:([^;]+);/);
    const mimeType = mimeMatch ? mimeMatch[1] : 'image/jpeg';
    blob = base64ToBlob(fileData, mimeType);
  } else {
    blob = fileData;
  }

  // Sanitize file name
  const cleanFileName = fileName.replace(/[^a-zA-Z0-9-_.]/g, '_');
  const filePath = `xuongan_samples/${Date.now()}_${cleanFileName}`;
  
  const storageRef = ref(storage, filePath);
  const snapshot = await uploadBytes(storageRef, blob);
  const fileUrl = await getDownloadURL(snapshot.ref);
  
  return { fileUrl, filePath };
}

/**
 * Delete an image from Firebase Cloud Storage by its file path
 */
export async function deleteImageFromFirebase(filePath: string): Promise<void> {
  if (!storage || !filePath) return;
  try {
    const storageRef = ref(storage, filePath);
    await deleteObject(storageRef);
    console.log("[Firebase Storage] Deleted old file successfully:", filePath);
  } catch (err) {
    console.warn("[Firebase Storage] Failed to delete file at path:", filePath, err);
  }
}

