/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import firebaseConfig from '../../firebase-applet-config.json';

const app = initializeApp(firebaseConfig);

// CRITICAL: The app will break without passing firestoreDatabaseId if specified
const dbId = (firebaseConfig as any).firestoreDatabaseId;

// Determine if we should bypass the sandbox database id in production or external contexts.
// Sandbox database IDs generated by AI Studio start with 'ai-studio-'.
// When built for production, deployed on GitHub Pages, or packaged as an Android APK,
// the application should fall back to standard '(default)' database ID since the sandbox database
// does not exist in the user's personal Firebase production project 'app-kho-an'.
const isForceDefaultDb = typeof window !== 'undefined' && localStorage.getItem("xuongan_force_default_db") === "true";

const isProductionUserApp = typeof window !== 'undefined' && (
  window.location.hostname.includes('github.io') ||
  window.location.protocol.startsWith('capacitor') ||
  window.location.protocol.startsWith('chrome-extension') ||
  window.location.protocol.startsWith('file') ||
  window.location.hostname === '' ||
  (!window.location.hostname.endsWith('run.app') && 
   !window.location.hostname.endsWith('googleusercontent.com') && 
   window.location.hostname !== 'localhost' && 
   window.location.hostname !== '127.0.5.1' &&
   window.location.hostname !== '127.0.0.1')
);

const finalDbId = (isForceDefaultDb || (dbId && dbId.startsWith('ai-studio-') && isProductionUserApp)) ? undefined : dbId;

export const db = finalDbId ? getFirestore(app, finalDbId) : getFirestore(app);
export const auth = getAuth(app);

// Namespace helpers for Group Collaboration & Database Pooling (Tính năng Nhóm & Kết hợp liên kết)
export function getNamespaceCollection(collectionName: string): string {
  if (typeof window === 'undefined') return collectionName;
  const groupCode = localStorage.getItem("xuongan_group_code") || "";
  const cleanCode = groupCode.trim().toUpperCase().replace(/[^A-Z0-9_-]/g, "");
  // We keep system logs separate if needed, but partition operational tables
  if (collectionName === 'login_notifications') {
    return collectionName;
  }
  return cleanCode ? `group_${cleanCode}_${collectionName}` : collectionName;
}

export function getSettingsDocId(): string {
  if (typeof window === 'undefined') return "global_settings";
  const groupCode = localStorage.getItem("xuongan_group_code") || "";
  const cleanCode = groupCode.trim().toUpperCase().replace(/[^A-Z0-9_-]/g, "");
  return cleanCode ? `settings_${cleanCode}` : "global_settings";
}

// Custom Error types and helpers as requested by Firebase Integration Skill
export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  };
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null): never {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
      tenantId: auth.currentUser?.tenantId,
      providerInfo: auth.currentUser?.providerData?.map(provider => ({
        providerId: provider.providerId,
        email: provider.email,
      })) || []
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

/**
 * Recursively cleans and sanitizes data before writing to Firestore,
 * ensuring no undefined fields are passed, which would crash Firestore.
 */
export function sanitizeDataForFirestore<T>(data: T): T {
  if (data === undefined) {
    return null as unknown as T;
  }
  if (data === null) {
    return null as unknown as T;
  }
  if (Array.isArray(data)) {
    return data.map(item => sanitizeDataForFirestore(item)) as unknown as T;
  }
  if (typeof data === 'object') {
    // Keep custom Date/Timestamp untouched
    if (data instanceof Date) {
      return data;
    }
    const sanitizedObj: any = {};
    for (const [key, val] of Object.entries(data)) {
      if (val !== undefined) {
        sanitizedObj[key] = sanitizeDataForFirestore(val);
      }
    }
    return sanitizedObj as T;
  }
  return data;
}

