name: Capgo Live Update

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-live-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Build App
        run: npm run build

      - name: Upload to Capgo
        env:
          CAPGO_TOKEN: ${{ secrets.CAPGO_API_KEY }}
        run: |
          npx @capgo/cli bundle upload \
          -a 9bc744d0-6da2-4d42-9d7e-441b4c25b763 \
          -c production
